version: '3.7'

services:
    server1:
        image: shen100/consul-nodejs:1.0.0
        hostname: consul-server1
        container_name: consul-server1
        networks:
            mynet:
                ipv4_address: 172.16.10.11
        volumes:
            - "${VOLUME_PREFIX}/server1/data:/consul/data"
            - "${VOLUME_PREFIX}/server1/log:/consul/log"
            - "${VOLUME_PREFIX}/server1/config:/consul/config"

    server2:
        image: shen100/consul-nodejs:1.0.0
        hostname: consul-server2
        container_name: consul-server2
        networks:
            mynet:
                ipv4_address: 172.16.10.12
        volumes:
            - "${VOLUME_PREFIX}/server2/data:/consul/data"
            - "${VOLUME_PREFIX}/server2/log:/consul/log"
            - "${VOLUME_PREFIX}/server2/config:/consul/config"

    server3:
        image: shen100/consul-nodejs:1.0.0
        hostname: consul-server3
        container_name: consul-server3
        networks:
            mynet:
                ipv4_address: 172.16.10.13
        volumes:
            - "${VOLUME_PREFIX}/server3/data:/consul/data"
            - "${VOLUME_PREFIX}/server3/log:/consul/log"
            - "${VOLUME_PREFIX}/server3/config:/consul/config"

    client1:
        image: shen100/consul-nodejs:1.0.0
        hostname: consul-client1
        container_name: consul-client1
        networks:
            mynet:
                ipv4_address: 172.16.10.21
        volumes:
            - "${VOLUME_PREFIX}/client1/data:/consul/data"
            - "${VOLUME_PREFIX}/client1/log:/consul/log"
            - "${VOLUME_PREFIX}/client1/config:/consul/config"
            - "${VOLUME_PREFIX}/client1/app:/consul/app"
        ports:
            - "8500:8500"
            - "3001:3000"

    client2:
        image: shen100/consul-nodejs:1.0.0
        hostname: consul-client2
        container_name: consul-client2
        networks:
            mynet:
                ipv4_address: 172.16.10.22
        volumes:
            - "${VOLUME_PREFIX}/client2/data:/consul/data"
            - "${VOLUME_PREFIX}/client2/log:/consul/log"
            - "${VOLUME_PREFIX}/client2/config:/consul/config"
            - "${VOLUME_PREFIX}/client2/app:/consul/app"
        ports:
            - "3002:3000"

networks:
    mynet:
        driver: bridge
        ipam:
            config:
            - subnet: 172.16.10.0/24